### ISSUE TITLE
[Feature request] Option to switch units

### ISSUE THREAD

**Issue by werdahias** [samtay/thesurf.in#1]
It would be nice if it was possible to switch units (ft -> m, °F -> °C).

**Comment by samtay** [comment]
Thanks for your suggestion! Just implemented and deployed this. See [docs](https://github.com/samtay/thesurf.in#units) for the options, but based on your request for m, C, you probably want `eu`: https://thesurf.in/?units=eu. It will mean that you are also getting back kph. Hopefully that's alright :shrug:  that's the granularity offered by the MSW API.

**Comment by werdahias** [comment]
Cool, thanks :)

**Comment by werdahias** [comment]
While the option works, the url seems to yield a broken result:

```
https://thesurf.in/4711?units=eu
error decoding response body: invalid type: floating point `-0`, expected i32 at line 1 column 16653
```

**Comment by samtay** [comment]
Thanks for the heads up, should be fixed now!
